import { chromium } from '@playwright/test';
const BASE = 'http://172.31.106.28:3000';
const CLIENT_ID = '63ed307c-aac4-4456-b9a5-14ae378f6cf2';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/login`, { waitUntil: 'networkidle' });
await page.getByRole('textbox', { name: /e-?mail/i }).fill('gerente@padaria.com.br');
await page.getByRole('textbox', { name: 'Senha' }).fill('Sprint6Valida!2026');
await page.getByRole('button', { name: /entrar/i }).click();
await page.waitForURL('**/clientes**', { timeout: 30000 });
console.log('pós-login URL =', page.url());
await page.goto(`${BASE}/clientes/${CLIENT_ID}/conciliacao`, { waitUntil: 'networkidle' });
await new Promise((r) => setTimeout(r, 3000));
console.log('URL final =', page.url());
console.log('#filter-month existe?', await page.locator('#filter-month').count());
console.log('inputs month:', await page.locator('input[type="month"]').count());
console.log('headings:', await page.locator('h1,h2').allInnerTexts());
console.log('body 1a linha:', (await page.locator('body').innerText()).slice(0, 300).replace(/\n/g, ' | '));
await browser.close();
