"""Modelos SQLAlchemy do projeto.

Importar Base e os modelos a partir daqui garante que o Alembic detecta
todos para autogenerate (`alembic revision --autogenerate`).
"""

from app.db.base import Base
from app.db.models.access_audit import AccessAudit
from app.db.models.accounting_file_generation import (
    ACCOUNTING_FILE_GENERATION_CHECKS,
    AccountingFileGeneration,
)
from app.db.models.anomaly_type import AnomalySeverity, AnomalyType
from app.db.models.client import IV_HEX_LENGTH, Client
from app.db.models.client_accounting_account import (
    ACCOUNTING_ACCOUNT_NAME_PAIR_CONSTRAINT,
    ACCOUNTING_ACCOUNT_TYPE_CONSTRAINT,
    MAX_ACCOUNTING_ACCOUNT_CLASSIFICATION_CHARS,
    MAX_ACCOUNTING_ACCOUNT_CODE_CHARS,
    MAX_ACCOUNTING_ACCOUNT_NAME_CHARS,
    UQ_ACCOUNTING_ACCOUNT_CLIENT_CODE,
    AccountingAccountType,
    ClientAccountingAccount,
    accounting_account_name_pair_check,
    accounting_account_type_check,
)
from app.db.models.client_assignment import (
    UQ_CLIENT_ASSIGNMENT_CLIENT_USER,
    UQ_CLIENT_ASSIGNMENT_PRIMARY,
    ClientAssignment,
    primary_assignment_index_predicate,
)
from app.db.models.client_category import (
    MAX_CATEGORY_NAME_CHARS,
    UQ_CLIENT_CATEGORY_ORGANIZATION_NAME,
    ClientCategory,
    ClientCategoryTone,
)
from app.db.models.client_chart_of_accounts import (
    CHART_OF_ACCOUNTS_STATUS_CONSTRAINT,
    MAX_ACCOUNT_CODE_CHARS,
    UQ_CHART_OF_ACCOUNTS_CLIENT_CODE,
    ChartOfAccountsStatus,
    ClientChartOfAccount,
    chart_of_accounts_status_check,
)
from app.db.models.client_connection import (
    CONNECTION_CREDENTIALS_PAIR_CONSTRAINT,
    CONNECTION_STATUS_CONSTRAINT,
    MAX_CONNECTION_LABEL_CHARS,
    UQ_CLIENT_CONNECTION_CLIENT_PROVIDER_LABEL,
    ClientConnection,
    ConnectionStatus,
    ProviderType,
    connection_credentials_pair_check,
    connection_status_check,
)
from app.db.models.client_file_category import (
    FILE_CATEGORY_CODE_PREFIX,
    FILE_CATEGORY_LABEL_PAIR_CONSTRAINT,
    UQ_CLIENT_FILE_CATEGORY_CLIENT_CODE,
    ClientFileCategory,
    file_category_label_pair_check,
    new_file_category_code,
)
from app.db.models.client_file_import import (
    FILE_HASH_HEX_LENGTH,
    FILE_IMPORT_COMPETENCE_CHECK,
    FILE_IMPORT_COMPETENCE_CONSTRAINT,
    UQ_CLIENT_FILE_IMPORT_CLIENT_COMPETENCE_HASH,
    ClientFileImport,
)
from app.db.models.client_glossary_entry import (
    MAX_CODE_CHARS,
    MAX_DESCRIPTION_CHARS,
    MAX_ENTRIES_PER_CLIENT,
    MAX_NAME_CHARS,
    ClientGlossaryEntry,
    GlossaryEntryKind,
)
from app.db.models.client_input_mapping import (
    INPUT_MAPPING_CATEGORY_COHERENT_CHECK,
    INPUT_MAPPING_CATEGORY_COHERENT_CONSTRAINT,
    INPUT_MAPPING_CSV_COHERENT_CHECK,
    INPUT_MAPPING_CSV_COHERENT_CONSTRAINT,
    INPUT_MAPPING_SIGN_COHERENT_CHECK,
    INPUT_MAPPING_SIGN_COHERENT_CONSTRAINT,
    MAX_INPUT_COLUMN_NAME_CHARS,
    MAX_NATURE_LITERAL_CHARS,
    UQ_CLIENT_INPUT_MAPPING_CLIENT,
    CategoryMode,
    ClientInputMapping,
    CsvDelimiter,
    DecimalSeparator,
    InputDateFormat,
    InputEncoding,
    InputFileFormat,
    SignConvention,
)
from app.db.models.client_mapping import (
    ClientMappingDecision,
    ClientMappingMaterialization,
    ClientMappingMaterializationItem,
    DecisionOrigin,
    DecisionType,
    MaterializedSituation,
)
from app.db.models.client_movement import (
    IX_CLIENT_MOVEMENT_CLIENT_COMPETENCE,
    MAX_MOVEMENT_CATEGORY_CODE_CHARS,
    MAX_MOVEMENT_DOCUMENT_CHARS,
    MAX_MOVEMENT_REF_CHARS,
    MAX_MOVEMENT_SOURCE_ID_CHARS,
    MAX_MOVEMENT_SOURCE_TYPE_CHARS,
    MOVEMENT_COMPETENCE_CHECK,
    MOVEMENT_COMPETENCE_CONSTRAINT,
    MOVEMENT_DESCRIPTION_PAIR_CONSTRAINT,
    MOVEMENT_STATUS_CONSTRAINT,
    UQ_CLIENT_MOVEMENT_SOURCE,
    ClientMovement,
    MovementStatus,
    movement_description_pair_check,
    movement_status_check,
)
from app.db.models.client_movement_sync import UQ_CLIENT_MOVEMENT_SYNC, ClientMovementSync
from app.db.models.client_source_account_binding import (
    UQ_SOURCE_ACCOUNT_BINDING,
    UQ_SOURCE_ACCOUNT_BINDING_DEFAULT,
    ClientSourceAccountBinding,
    default_binding_index_predicate,
)
from app.db.models.client_title import (
    CLOSED_TITLE_STATUSES,
    IX_CLIENT_TITLE_CLIENT_DUE_DATE,
    MAX_TITLE_CODE_CHARS,
    MAX_TITLE_DOCUMENT_CHARS,
    MAX_TITLE_EXTERNAL_ID_CHARS,
    TITLE_STATUS_CONSTRAINT,
    TITLE_TYPE_CONSTRAINT,
    UQ_CLIENT_TITLE_CLIENT_EXTERNAL_ID,
    ClientTitle,
    TitleStatus,
    TitleType,
    title_status_check,
    title_type_check,
)
from app.db.models.export_layout import (
    UQ_EXPORT_LAYOUT_ORG_NAME,
    UQ_EXPORT_LAYOUT_VERSION,
    ExportLayout,
    ExportLayoutVersion,
)
from app.db.models.mapping_catalog import (
    ACCOUNTING_DESTINATION_TYPE,
    DEFAULT_DESTINATION_TYPES,
    INHERITING_DESTINATION_TYPE,
    MappingDestination,
    MappingTarget,
)
from app.db.models.notification import Notification, NotificationType
from app.db.models.omie_account_cache import OmieAccountCache, OmieAccountType
from app.db.models.organization import (
    HOLOGRAM_ORGANIZATION_ID,
    HOLOGRAM_ORGANIZATION_NAME,
    MAX_ORGANIZATION_NAME_CHARS,
    UQ_ORGANIZATION_NAME,
    Organization,
    organization_id_server_default,
)
from app.db.models.reconciliation_anomaly import (
    AnomalyDetectedBy,
    AnomalyReviewVerdict,
    ReconciliationAnomaly,
)
from app.db.models.reconciliation_file import ReconciliationFile, ReconciliationFileStatus
from app.db.models.reconciliation_file_entry import (
    FileEntrySituation,
    FileEntryUserAction,
    ReconciliationFileEntry,
)
from app.db.models.reconciliation_omie_entry import (
    OmieEntryStatus,
    OmieEntryUserAction,
    ReconciliationOmieEntry,
)
from app.db.models.reconciliation_omie_posting import (
    COD_INT_LANC_MAX_LENGTH,
    OmiePostingStatus,
    ReconciliationOmiePosting,
)
from app.db.models.reconciliation_session import (
    ReconciliationSession,
    ReconciliationStatus,
    SessionAccountType,
)
from app.db.models.title_context import (
    CONTEXT_TYPES_NOT_DELINQUENT,
    IX_TITLE_CONTEXT_TITLE_ID_CREATED_AT,
    TITLE_CONTEXT_TYPE_CONSTRAINT,
    TitleContext,
    TitleContextType,
    title_context_type_check,
)
from app.db.models.usage_event import UsageEvent
from app.db.models.user import (
    CLIENT_ROLES,
    PLATFORM_ROLES,
    SCOPE_CONSISTENCY_CHECK,
    SCOPE_CONSISTENCY_CONSTRAINT,
    SYSTEM_ROLES,
    ClientUserRole,
    SystemUserRole,
    User,
    UserRole,
    UserScope,
)
from app.db.models.user_client_favorite import UQ_USER_CLIENT_FAVORITE, UserClientFavorite

__all__ = [
    "ACCOUNTING_ACCOUNT_NAME_PAIR_CONSTRAINT",
    "ACCOUNTING_ACCOUNT_TYPE_CONSTRAINT",
    "ACCOUNTING_DESTINATION_TYPE",
    "ACCOUNTING_FILE_GENERATION_CHECKS",
    "CHART_OF_ACCOUNTS_STATUS_CONSTRAINT",
    "CLIENT_ROLES",
    "CLOSED_TITLE_STATUSES",
    "COD_INT_LANC_MAX_LENGTH",
    "CONNECTION_CREDENTIALS_PAIR_CONSTRAINT",
    "CONNECTION_STATUS_CONSTRAINT",
    "CONTEXT_TYPES_NOT_DELINQUENT",
    "DEFAULT_DESTINATION_TYPES",
    "FILE_CATEGORY_CODE_PREFIX",
    "FILE_CATEGORY_LABEL_PAIR_CONSTRAINT",
    "FILE_HASH_HEX_LENGTH",
    "FILE_IMPORT_COMPETENCE_CHECK",
    "FILE_IMPORT_COMPETENCE_CONSTRAINT",
    "HOLOGRAM_ORGANIZATION_ID",
    "HOLOGRAM_ORGANIZATION_NAME",
    "INHERITING_DESTINATION_TYPE",
    "INPUT_MAPPING_CATEGORY_COHERENT_CHECK",
    "INPUT_MAPPING_CATEGORY_COHERENT_CONSTRAINT",
    "INPUT_MAPPING_CSV_COHERENT_CHECK",
    "INPUT_MAPPING_CSV_COHERENT_CONSTRAINT",
    "INPUT_MAPPING_SIGN_COHERENT_CHECK",
    "INPUT_MAPPING_SIGN_COHERENT_CONSTRAINT",
    "IV_HEX_LENGTH",
    "IX_CLIENT_MOVEMENT_CLIENT_COMPETENCE",
    "IX_CLIENT_TITLE_CLIENT_DUE_DATE",
    "IX_TITLE_CONTEXT_TITLE_ID_CREATED_AT",
    "MAX_ACCOUNTING_ACCOUNT_CLASSIFICATION_CHARS",
    "MAX_ACCOUNTING_ACCOUNT_CODE_CHARS",
    "MAX_ACCOUNTING_ACCOUNT_NAME_CHARS",
    "MAX_ACCOUNT_CODE_CHARS",
    "MAX_CATEGORY_NAME_CHARS",
    "MAX_CODE_CHARS",
    "MAX_CONNECTION_LABEL_CHARS",
    "MAX_DESCRIPTION_CHARS",
    "MAX_ENTRIES_PER_CLIENT",
    "MAX_INPUT_COLUMN_NAME_CHARS",
    "MAX_MOVEMENT_CATEGORY_CODE_CHARS",
    "MAX_MOVEMENT_DOCUMENT_CHARS",
    "MAX_MOVEMENT_REF_CHARS",
    "MAX_MOVEMENT_SOURCE_ID_CHARS",
    "MAX_MOVEMENT_SOURCE_TYPE_CHARS",
    "MAX_NAME_CHARS",
    "MAX_NATURE_LITERAL_CHARS",
    "MAX_ORGANIZATION_NAME_CHARS",
    "MAX_TITLE_CODE_CHARS",
    "MAX_TITLE_DOCUMENT_CHARS",
    "MAX_TITLE_EXTERNAL_ID_CHARS",
    "MOVEMENT_COMPETENCE_CHECK",
    "MOVEMENT_COMPETENCE_CONSTRAINT",
    "MOVEMENT_DESCRIPTION_PAIR_CONSTRAINT",
    "MOVEMENT_STATUS_CONSTRAINT",
    "PLATFORM_ROLES",
    "SCOPE_CONSISTENCY_CHECK",
    "SCOPE_CONSISTENCY_CONSTRAINT",
    "SYSTEM_ROLES",
    "TITLE_CONTEXT_TYPE_CONSTRAINT",
    "TITLE_STATUS_CONSTRAINT",
    "TITLE_TYPE_CONSTRAINT",
    "UQ_ACCOUNTING_ACCOUNT_CLIENT_CODE",
    "UQ_CHART_OF_ACCOUNTS_CLIENT_CODE",
    "UQ_CLIENT_ASSIGNMENT_CLIENT_USER",
    "UQ_CLIENT_ASSIGNMENT_PRIMARY",
    "UQ_CLIENT_CATEGORY_ORGANIZATION_NAME",
    "UQ_CLIENT_CONNECTION_CLIENT_PROVIDER_LABEL",
    "UQ_CLIENT_FILE_CATEGORY_CLIENT_CODE",
    "UQ_CLIENT_FILE_IMPORT_CLIENT_COMPETENCE_HASH",
    "UQ_CLIENT_INPUT_MAPPING_CLIENT",
    "UQ_CLIENT_MOVEMENT_SOURCE",
    "UQ_CLIENT_MOVEMENT_SYNC",
    "UQ_CLIENT_TITLE_CLIENT_EXTERNAL_ID",
    "UQ_EXPORT_LAYOUT_ORG_NAME",
    "UQ_EXPORT_LAYOUT_VERSION",
    "UQ_ORGANIZATION_NAME",
    "UQ_SOURCE_ACCOUNT_BINDING",
    "UQ_SOURCE_ACCOUNT_BINDING_DEFAULT",
    "UQ_USER_CLIENT_FAVORITE",
    "AccessAudit",
    "AccountingAccountType",
    "AccountingFileGeneration",
    "AnomalyDetectedBy",
    "AnomalyReviewVerdict",
    "AnomalySeverity",
    "AnomalyType",
    "Base",
    "CategoryMode",
    "ChartOfAccountsStatus",
    "Client",
    "ClientAccountingAccount",
    "ClientAssignment",
    "ClientCategory",
    "ClientCategoryTone",
    "ClientChartOfAccount",
    "ClientConnection",
    "ClientFileCategory",
    "ClientFileImport",
    "ClientGlossaryEntry",
    "ClientInputMapping",
    "ClientMappingDecision",
    "ClientMappingMaterialization",
    "ClientMappingMaterializationItem",
    "ClientMovement",
    "ClientMovementSync",
    "ClientSourceAccountBinding",
    "ClientTitle",
    "ClientUserRole",
    "ConnectionStatus",
    "CsvDelimiter",
    "DecimalSeparator",
    "DecisionOrigin",
    "DecisionType",
    "ExportLayout",
    "ExportLayoutVersion",
    "FileEntrySituation",
    "FileEntryUserAction",
    "GlossaryEntryKind",
    "InputDateFormat",
    "InputEncoding",
    "InputFileFormat",
    "MappingDestination",
    "MappingTarget",
    "MaterializedSituation",
    "MovementStatus",
    "Notification",
    "NotificationType",
    "OmieAccountCache",
    "OmieAccountType",
    "OmieEntryStatus",
    "OmieEntryUserAction",
    "OmiePostingStatus",
    "Organization",
    "ProviderType",
    "ReconciliationAnomaly",
    "ReconciliationFile",
    "ReconciliationFileEntry",
    "ReconciliationFileStatus",
    "ReconciliationOmieEntry",
    "ReconciliationOmiePosting",
    "ReconciliationSession",
    "ReconciliationStatus",
    "SessionAccountType",
    "SignConvention",
    "SystemUserRole",
    "TitleContext",
    "TitleContextType",
    "TitleStatus",
    "TitleType",
    "UsageEvent",
    "User",
    "UserClientFavorite",
    "UserRole",
    "UserScope",
    "accounting_account_name_pair_check",
    "accounting_account_type_check",
    "chart_of_accounts_status_check",
    "connection_credentials_pair_check",
    "connection_status_check",
    "default_binding_index_predicate",
    "file_category_label_pair_check",
    "movement_description_pair_check",
    "movement_status_check",
    "new_file_category_code",
    "organization_id_server_default",
    "primary_assignment_index_predicate",
    "title_context_type_check",
    "title_status_check",
    "title_type_check",
]
