"""Modelos SQLAlchemy do projeto.

Importar Base e os modelos a partir daqui garante que o Alembic detecta
todos para autogenerate (`alembic revision --autogenerate`).
"""

from app.db.base import Base
from app.db.models.access_audit import AccessAudit
from app.db.models.anomaly_type import AnomalySeverity, AnomalyType
from app.db.models.client import IV_HEX_LENGTH, Client
from app.db.models.client_assignment import (
    UQ_CLIENT_ASSIGNMENT_CLIENT_USER,
    UQ_CLIENT_ASSIGNMENT_PRIMARY,
    ClientAssignment,
    primary_assignment_index_predicate,
)
from app.db.models.client_category import (
    MAX_CATEGORY_NAME_CHARS,
    UQ_CLIENT_CATEGORY_ORGANIZATION_NAME,
    ClientCategory,
    ClientCategoryTone,
)
from app.db.models.client_chart_of_accounts import (
    CHART_OF_ACCOUNTS_STATUS_CONSTRAINT,
    MAX_ACCOUNT_CODE_CHARS,
    UQ_CHART_OF_ACCOUNTS_CLIENT_CODE,
    ChartOfAccountsStatus,
    ClientChartOfAccount,
    chart_of_accounts_status_check,
)
from app.db.models.client_connection import (
    CONNECTION_CREDENTIALS_PAIR_CONSTRAINT,
    CONNECTION_STATUS_CONSTRAINT,
    MAX_CONNECTION_LABEL_CHARS,
    UQ_CLIENT_CONNECTION_CLIENT_PROVIDER_LABEL,
    ClientConnection,
    ConnectionStatus,
    ProviderType,
    connection_credentials_pair_check,
    connection_status_check,
)
from app.db.models.client_glossary_entry import (
    MAX_CODE_CHARS,
    MAX_DESCRIPTION_CHARS,
    MAX_ENTRIES_PER_CLIENT,
    MAX_NAME_CHARS,
    ClientGlossaryEntry,
    GlossaryEntryKind,
)
from app.db.models.client_mapping import (
    ClientMappingDecision,
    ClientMappingMaterialization,
    ClientMappingMaterializationItem,
    DecisionOrigin,
    DecisionType,
    MaterializedSituation,
)
from app.db.models.client_movement import (
    IX_CLIENT_MOVEMENT_CLIENT_COMPETENCE,
    MAX_MOVEMENT_CATEGORY_CODE_CHARS,
    MAX_MOVEMENT_REF_CHARS,
    MAX_MOVEMENT_SOURCE_ID_CHARS,
    MAX_MOVEMENT_SOURCE_TYPE_CHARS,
    MOVEMENT_COMPETENCE_CHECK,
    MOVEMENT_COMPETENCE_CONSTRAINT,
    MOVEMENT_STATUS_CONSTRAINT,
    UQ_CLIENT_MOVEMENT_SOURCE,
    ClientMovement,
    MovementStatus,
    movement_status_check,
)
from app.db.models.client_movement_sync import UQ_CLIENT_MOVEMENT_SYNC, ClientMovementSync
from app.db.models.client_title import (
    CLOSED_TITLE_STATUSES,
    IX_CLIENT_TITLE_CLIENT_DUE_DATE,
    MAX_TITLE_CODE_CHARS,
    MAX_TITLE_DOCUMENT_CHARS,
    MAX_TITLE_EXTERNAL_ID_CHARS,
    TITLE_STATUS_CONSTRAINT,
    TITLE_TYPE_CONSTRAINT,
    UQ_CLIENT_TITLE_CLIENT_EXTERNAL_ID,
    ClientTitle,
    TitleStatus,
    TitleType,
    title_status_check,
    title_type_check,
)
from app.db.models.mapping_catalog import (
    DEFAULT_DESTINATION_TYPES,
    INHERITING_DESTINATION_TYPE,
    MappingDestination,
    MappingTarget,
)
from app.db.models.notification import Notification, NotificationType
from app.db.models.omie_account_cache import OmieAccountCache, OmieAccountType
from app.db.models.organization import (
    HOLOGRAM_ORGANIZATION_ID,
    HOLOGRAM_ORGANIZATION_NAME,
    MAX_ORGANIZATION_NAME_CHARS,
    UQ_ORGANIZATION_NAME,
    Organization,
    organization_id_server_default,
)
from app.db.models.reconciliation_anomaly import (
    AnomalyDetectedBy,
    AnomalyReviewVerdict,
    ReconciliationAnomaly,
)
from app.db.models.reconciliation_file import ReconciliationFile, ReconciliationFileStatus
from app.db.models.reconciliation_file_entry import (
    FileEntrySituation,
    FileEntryUserAction,
    ReconciliationFileEntry,
)
from app.db.models.reconciliation_omie_entry import (
    OmieEntryStatus,
    OmieEntryUserAction,
    ReconciliationOmieEntry,
)
from app.db.models.reconciliation_omie_posting import (
    COD_INT_LANC_MAX_LENGTH,
    OmiePostingStatus,
    ReconciliationOmiePosting,
)
from app.db.models.reconciliation_session import (
    ReconciliationSession,
    ReconciliationStatus,
    SessionAccountType,
)
from app.db.models.title_context import (
    CONTEXT_TYPES_NOT_DELINQUENT,
    IX_TITLE_CONTEXT_TITLE_ID_CREATED_AT,
    TITLE_CONTEXT_TYPE_CONSTRAINT,
    TitleContext,
    TitleContextType,
    title_context_type_check,
)
from app.db.models.usage_event import UsageEvent
from app.db.models.user import (
    CLIENT_ROLES,
    PLATFORM_ROLES,
    SCOPE_CONSISTENCY_CHECK,
    SCOPE_CONSISTENCY_CONSTRAINT,
    SYSTEM_ROLES,
    ClientUserRole,
    SystemUserRole,
    User,
    UserRole,
    UserScope,
)
from app.db.models.user_client_favorite import UQ_USER_CLIENT_FAVORITE, UserClientFavorite

__all__ = [
    "CHART_OF_ACCOUNTS_STATUS_CONSTRAINT",
    "CLIENT_ROLES",
    "CLOSED_TITLE_STATUSES",
    "COD_INT_LANC_MAX_LENGTH",
    "CONNECTION_CREDENTIALS_PAIR_CONSTRAINT",
    "CONNECTION_STATUS_CONSTRAINT",
    "CONTEXT_TYPES_NOT_DELINQUENT",
    "DEFAULT_DESTINATION_TYPES",
    "HOLOGRAM_ORGANIZATION_ID",
    "HOLOGRAM_ORGANIZATION_NAME",
    "INHERITING_DESTINATION_TYPE",
    "IV_HEX_LENGTH",
    "IX_CLIENT_MOVEMENT_CLIENT_COMPETENCE",
    "IX_CLIENT_TITLE_CLIENT_DUE_DATE",
    "IX_TITLE_CONTEXT_TITLE_ID_CREATED_AT",
    "MAX_ACCOUNT_CODE_CHARS",
    "MAX_CATEGORY_NAME_CHARS",
    "MAX_CODE_CHARS",
    "MAX_CONNECTION_LABEL_CHARS",
    "MAX_DESCRIPTION_CHARS",
    "MAX_ENTRIES_PER_CLIENT",
    "MAX_MOVEMENT_CATEGORY_CODE_CHARS",
    "MAX_MOVEMENT_REF_CHARS",
    "MAX_MOVEMENT_SOURCE_ID_CHARS",
    "MAX_MOVEMENT_SOURCE_TYPE_CHARS",
    "MAX_NAME_CHARS",
    "MAX_ORGANIZATION_NAME_CHARS",
    "MAX_TITLE_CODE_CHARS",
    "MAX_TITLE_DOCUMENT_CHARS",
    "MAX_TITLE_EXTERNAL_ID_CHARS",
    "MOVEMENT_COMPETENCE_CHECK",
    "MOVEMENT_COMPETENCE_CONSTRAINT",
    "MOVEMENT_STATUS_CONSTRAINT",
    "PLATFORM_ROLES",
    "SCOPE_CONSISTENCY_CHECK",
    "SCOPE_CONSISTENCY_CONSTRAINT",
    "SYSTEM_ROLES",
    "TITLE_CONTEXT_TYPE_CONSTRAINT",
    "TITLE_STATUS_CONSTRAINT",
    "TITLE_TYPE_CONSTRAINT",
    "UQ_CHART_OF_ACCOUNTS_CLIENT_CODE",
    "UQ_CLIENT_ASSIGNMENT_CLIENT_USER",
    "UQ_CLIENT_ASSIGNMENT_PRIMARY",
    "UQ_CLIENT_CATEGORY_ORGANIZATION_NAME",
    "UQ_CLIENT_CONNECTION_CLIENT_PROVIDER_LABEL",
    "UQ_CLIENT_MOVEMENT_SOURCE",
    "UQ_CLIENT_MOVEMENT_SYNC",
    "UQ_CLIENT_TITLE_CLIENT_EXTERNAL_ID",
    "UQ_ORGANIZATION_NAME",
    "UQ_USER_CLIENT_FAVORITE",
    "AccessAudit",
    "AnomalyDetectedBy",
    "AnomalyReviewVerdict",
    "AnomalySeverity",
    "AnomalyType",
    "Base",
    "ChartOfAccountsStatus",
    "Client",
    "ClientAssignment",
    "ClientCategory",
    "ClientCategoryTone",
    "ClientChartOfAccount",
    "ClientConnection",
    "ClientGlossaryEntry",
    "ClientMappingDecision",
    "ClientMappingMaterialization",
    "ClientMappingMaterializationItem",
    "ClientMovement",
    "ClientMovementSync",
    "ClientTitle",
    "ClientUserRole",
    "ConnectionStatus",
    "DecisionOrigin",
    "DecisionType",
    "FileEntrySituation",
    "FileEntryUserAction",
    "GlossaryEntryKind",
    "MappingDestination",
    "MappingTarget",
    "MaterializedSituation",
    "MovementStatus",
    "Notification",
    "NotificationType",
    "OmieAccountCache",
    "OmieAccountType",
    "OmieEntryStatus",
    "OmieEntryUserAction",
    "OmiePostingStatus",
    "Organization",
    "ProviderType",
    "ReconciliationAnomaly",
    "ReconciliationFile",
    "ReconciliationFileEntry",
    "ReconciliationFileStatus",
    "ReconciliationOmieEntry",
    "ReconciliationOmiePosting",
    "ReconciliationSession",
    "ReconciliationStatus",
    "SessionAccountType",
    "SystemUserRole",
    "TitleContext",
    "TitleContextType",
    "TitleStatus",
    "TitleType",
    "UsageEvent",
    "User",
    "UserClientFavorite",
    "UserRole",
    "UserScope",
    "chart_of_accounts_status_check",
    "connection_credentials_pair_check",
    "connection_status_check",
    "movement_status_check",
    "organization_id_server_default",
    "primary_assignment_index_predicate",
    "title_context_type_check",
    "title_status_check",
    "title_type_check",
]
