"""initial schema (s2)

Revision ID: 86d463d5c022
Revises:
Create Date: 2026-04-25 17:42:26.483515+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86d463d5c022"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_types",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_anomaly_types")),
    )
    op.create_index(op.f("ix_anomaly_types_code"), "anomaly_types", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("omie_app_key_encrypted", sa.Text(), nullable=False),
        sa.Column("omie_app_key_iv", sa.String(length=24), nullable=False),
        sa.Column("omie_app_secret_encrypted", sa.Text(), nullable=False),
        sa.Column("omie_app_secret_iv", sa.String(length=24), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_clients_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_name"), "clients", ["name"], unique=False)
    op.create_table(
        "client_assignments",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assigned_by", sa.UUID(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name=op.f("fk_client_assignments_assigned_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_client_assignments_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_client_assignments_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_assignments")),
    )
    op.create_index(
        op.f("ix_client_assignments_client_id"), "client_assignments", ["client_id"], unique=True
    )
    op.create_index(
        op.f("ix_client_assignments_user_id"), "client_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "omie_accounts_cache",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("omie_conta_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("bank_name", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=10), nullable=False),
        sa.Column(
            "synced_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_omie_accounts_cache_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_omie_accounts_cache")),
        sa.UniqueConstraint("client_id", "omie_conta_id", name="uq_omie_accounts_client_conta"),
    )
    op.create_index(
        op.f("ix_omie_accounts_cache_client_id"), "omie_accounts_cache", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_omie_accounts_cache_synced_at"), "omie_accounts_cache", ["synced_at"], unique=False
    )
    op.create_table(
        "reconciliation_sessions",
        sa.Column("client_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("omie_conta_id", sa.BigInteger(), nullable=False),
        sa.Column("reference_month", sa.Date(), nullable=False),
        sa.Column("date_tolerance_days", sa.SmallInteger(), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("balance_start", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("balance_end_file", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("balance_end_omie", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("balance_difference", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("total_file_entries", sa.Integer(), nullable=False),
        sa.Column("conciliated_count", sa.Integer(), nullable=False),
        sa.Column("sem_omie_count", sa.Integer(), nullable=False),
        sa.Column("omie_sem_arquivo_count", sa.Integer(), nullable=False),
        sa.Column("anomaly_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_reconciliation_sessions_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_reconciliation_sessions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_sessions")),
        sa.UniqueConstraint(
            "client_id",
            "omie_conta_id",
            "reference_month",
            "file_hash",
            name="uq_recon_sessions_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_reconciliation_sessions_client_id"),
        "reconciliation_sessions",
        ["client_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_sessions_reference_month"),
        "reconciliation_sessions",
        ["reference_month"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_sessions_status"),
        "reconciliation_sessions",
        ["status"],
        unique=False,
    )
    op.create_table(
        "reconciliation_file_entries",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("description_encrypted", sa.Text(), nullable=False),
        sa.Column("description_iv", sa.String(length=24), nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("situation", sa.String(length=20), nullable=False),
        sa.Column("omie_lancamento_id", sa.BigInteger(), nullable=True),
        sa.Column("user_action", sa.String(length=20), nullable=True),
        sa.Column("user_note_encrypted", sa.Text(), nullable=True),
        sa.Column("user_note_iv", sa.String(length=24), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["reconciliation_sessions.id"],
            name=op.f("fk_reconciliation_file_entries_session_id_reconciliation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_file_entries")),
    )
    op.create_index(
        op.f("ix_reconciliation_file_entries_amount"),
        "reconciliation_file_entries",
        ["amount"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_file_entries_session_id"),
        "reconciliation_file_entries",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_file_entries_situation"),
        "reconciliation_file_entries",
        ["situation"],
        unique=False,
    )
    op.create_table(
        "reconciliation_omie_entries",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("omie_lancamento_id", sa.BigInteger(), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("omie_status", sa.String(length=30), nullable=False),
        sa.Column("user_action", sa.String(length=20), nullable=True),
        sa.Column("user_note_encrypted", sa.Text(), nullable=True),
        sa.Column("user_note_iv", sa.String(length=24), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["reconciliation_sessions.id"],
            name=op.f("fk_reconciliation_omie_entries_session_id_reconciliation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_omie_entries")),
    )
    op.create_index(
        op.f("ix_reconciliation_omie_entries_session_id"),
        "reconciliation_omie_entries",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_anomalies",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("anomaly_type_id", sa.UUID(), nullable=False),
        sa.Column("file_entry_id", sa.UUID(), nullable=True),
        sa.Column("omie_entry_id", sa.UUID(), nullable=True),
        sa.Column("detected_by", sa.String(length=20), nullable=False),
        sa.Column("context_encrypted", sa.Text(), nullable=True),
        sa.Column("context_iv", sa.String(length=24), nullable=True),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("resolution_note_encrypted", sa.Text(), nullable=True),
        sa.Column("resolution_note_iv", sa.String(length=24), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["anomaly_type_id"],
            ["anomaly_types.id"],
            name=op.f("fk_reconciliation_anomalies_anomaly_type_id_anomaly_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["file_entry_id"],
            ["reconciliation_file_entries.id"],
            name=op.f("fk_reconciliation_anomalies_file_entry_id_reconciliation_file_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["omie_entry_id"],
            ["reconciliation_omie_entries.id"],
            name=op.f("fk_reconciliation_anomalies_omie_entry_id_reconciliation_omie_entries"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["reconciliation_sessions.id"],
            name=op.f("fk_reconciliation_anomalies_session_id_reconciliation_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_anomalies")),
    )
    op.create_index(
        op.f("ix_reconciliation_anomalies_resolved"),
        "reconciliation_anomalies",
        ["resolved"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconciliation_anomalies_session_id"),
        "reconciliation_anomalies",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reconciliation_anomalies_session_id"), table_name="reconciliation_anomalies"
    )
    op.drop_index(
        op.f("ix_reconciliation_anomalies_resolved"), table_name="reconciliation_anomalies"
    )
    op.drop_table("reconciliation_anomalies")
    op.drop_index(
        op.f("ix_reconciliation_omie_entries_session_id"), table_name="reconciliation_omie_entries"
    )
    op.drop_table("reconciliation_omie_entries")
    op.drop_index(
        op.f("ix_reconciliation_file_entries_situation"), table_name="reconciliation_file_entries"
    )
    op.drop_index(
        op.f("ix_reconciliation_file_entries_session_id"), table_name="reconciliation_file_entries"
    )
    op.drop_index(
        op.f("ix_reconciliation_file_entries_amount"), table_name="reconciliation_file_entries"
    )
    op.drop_table("reconciliation_file_entries")
    op.drop_index(op.f("ix_reconciliation_sessions_status"), table_name="reconciliation_sessions")
    op.drop_index(
        op.f("ix_reconciliation_sessions_reference_month"), table_name="reconciliation_sessions"
    )
    op.drop_index(
        op.f("ix_reconciliation_sessions_client_id"), table_name="reconciliation_sessions"
    )
    op.drop_table("reconciliation_sessions")
    op.drop_index(op.f("ix_omie_accounts_cache_synced_at"), table_name="omie_accounts_cache")
    op.drop_index(op.f("ix_omie_accounts_cache_client_id"), table_name="omie_accounts_cache")
    op.drop_table("omie_accounts_cache")
    op.drop_index(op.f("ix_client_assignments_user_id"), table_name="client_assignments")
    op.drop_index(op.f("ix_client_assignments_client_id"), table_name="client_assignments")
    op.drop_table("client_assignments")
    op.drop_index(op.f("ix_clients_name"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_anomaly_types_code"), table_name="anomaly_types")
    op.drop_table("anomaly_types")
    # ### end Alembic commands ###
