"""s7: add omie_accounts_synced_at to clients

Revision ID: c8f3407fb8d3
Revises: 86d463d5c022
Create Date: 2026-04-29 18:49:03.116711+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8f3407fb8d3"
down_revision: str | None = "86d463d5c022"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients", sa.Column("omie_accounts_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "omie_accounts_synced_at")
    # ### end Alembic commands ###
